name: First Workflow
on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3 # Update to version 3 of actions/checkout

      - name: Install Node.js
        uses: actions/setup-node@v4 # Update to a newer version of actions/setup-node
        with:
          node-version: "20" # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install
      - name: List github context object
        run: echo "${{ toJson(github) }}"
      # - name: Run Tests
      #   run: npm test
